apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cleanupimagesonhostnode
  name: cleanupimagesonhostnode
spec:
  selector:
    matchLabels:
      app: cleanupimagesonhostnode
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cleanupimagesonhostnode
    spec:
      containers:
      - image: nginx
        name: nginx
        securityContext:
            privileged: true        
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -c
          - |
            echo "cleanup images started"
            crictl rmi -prune
            echo "cleanup images completed"
            sleep 100000s
      restartPolicy: Always
      hostPID: true
