apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
            - name: POSTGRES_USER
              value: postgresuser
            - name: POSTGRES_PASSWORD
              value: postgrespwd
            - name: POSTGRES_DB
              value: postgresdb
            - name: PGDATA
              value: /var/lib/postgresql/backup
        volumeMounts:
          - name: database
            mountPath: /var/lib/postgresql
            subPath: backup
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: pvc-postgre